"""
Core data models for the multi-agent data analyzer system.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Any, Optional, Tuple
import pandas as pd

from .enums import MessageType, Priority, DataType, RiskLevel, AnalysisState


@dataclass
class AgentMessage:
    """Message structure for inter-agent communication."""
    sender: str
    recipient: str
    message_type: MessageType
    content: Dict[str, Any]
    timestamp: datetime = field(default_factory=datetime.now)
    correlation_id: str = ""
    priority: Priority = Priority.MEDIUM

    def to_dict(self) -> Dict[str, Any]:
        """Convert message to dictionary for JSON serialization."""
        return {
            "sender": self.sender,
            "recipient": self.recipient,
            "message_type": self.message_type.name,
            "content": self.content,
            "timestamp": self.timestamp.isoformat(),
            "correlation_id": self.correlation_id,
            "priority": self.priority.name
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'AgentMessage':
        """Create message from dictionary."""
        return cls(
            sender=data["sender"],
            recipient=data["recipient"],
            message_type=MessageType[data["message_type"]],
            content=data["content"],
            timestamp=datetime.fromisoformat(data["timestamp"]),
            correlation_id=data["correlation_id"],
            priority=Priority[data["priority"]]
        )


@dataclass
class DataProfile:
    """Profile information about a dataset."""
    row_count: int
    column_count: int
    data_types: Dict[str, str]
    missing_values: Dict[str, int]
    unique_values: Dict[str, int]
    memory_usage: float
    sample_data: Optional[pd.DataFrame] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "row_count": self.row_count,
            "column_count": self.column_count,
            "data_types": self.data_types,
            "missing_values": self.missing_values,
            "unique_values": self.unique_values,
            "memory_usage": self.memory_usage,
            "has_sample_data": self.sample_data is not None
        }


@dataclass
class StatisticalSummary:
    """Statistical summary of dataset analysis."""
    descriptive_stats: Dict[str, Dict[str, float]]
    correlations: Optional[pd.DataFrame] = None
    outliers: Dict[str, List[Any]] = field(default_factory=dict)
    distribution_tests: Dict[str, Dict[str, float]] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "descriptive_stats": self.descriptive_stats,
            "correlations": self.correlations.to_dict() if self.correlations is not None else None,
            "outliers": self.outliers,
            "distribution_tests": self.distribution_tests
        }


@dataclass
class Recommendation:
    """A recommendation generated by the decision agent."""
    id: str
    title: str
    description: str
    priority: Priority
    estimated_impact: float
    required_resources: List[str]
    timeline: str
    risk_level: RiskLevel
    supporting_evidence: List[str]

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description,
            "priority": self.priority.name,
            "estimated_impact": self.estimated_impact,
            "required_resources": self.required_resources,
            "timeline": self.timeline,
            "risk_level": self.risk_level.name,
            "supporting_evidence": self.supporting_evidence
        }


@dataclass
class Report:
    """Final report structure."""
    executive_summary: str
    methodology: str
    key_findings: List[str]
    recommendations: List[Recommendation]
    technical_details: Dict[str, Any]
    visualizations: List[str]
    appendices: Dict[str, Any]
    generated_at: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "executive_summary": self.executive_summary,
            "methodology": self.methodology,
            "key_findings": self.key_findings,
            "recommendations": [rec.to_dict() for rec in self.recommendations],
            "technical_details": self.technical_details,
            "visualizations": self.visualizations,
            "appendices": self.appendices,
            "generated_at": self.generated_at.isoformat()
        }


@dataclass
class ColumnDefinition:
    """Definition of a column in the data dictionary."""
    name: str
    data_type: DataType
    description: str
    unit: Optional[str] = None
    valid_range: Optional[Tuple[float, float]] = None
    categorical_values: Optional[List[str]] = None
    is_nullable: bool = True
    relationships: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "name": self.name,
            "data_type": self.data_type.name,
            "description": self.description,
            "unit": self.unit,
            "valid_range": self.valid_range,
            "categorical_values": self.categorical_values,
            "is_nullable": self.is_nullable,
            "relationships": self.relationships
        }


@dataclass
class DataSchema:
    """Schema definition for a dataset."""
    columns: Dict[str, ColumnDefinition]
    primary_keys: List[str] = field(default_factory=list)
    foreign_keys: Dict[str, str] = field(default_factory=dict)
    business_rules: List[str] = field(default_factory=list)
    data_quality_rules: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "columns": {name: col.to_dict() for name, col in self.columns.items()},
            "primary_keys": self.primary_keys,
            "foreign_keys": self.foreign_keys,
            "business_rules": self.business_rules,
            "data_quality_rules": self.data_quality_rules
        }


@dataclass
class ValidationResult:
    """Result of a validation operation."""
    is_valid: bool
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "is_valid": self.is_valid,
            "errors": self.errors,
            "warnings": self.warnings,
            "metadata": self.metadata
        }